language: go

sudo: required

go:
  - 1.6
  
services:
  - docker

before_install:  
  - export APP_VERSION=`git describe --tag --long | awk -F- '{print $1"."$2}'`
  
script: 
  - go test .
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-X main.AppVersion=$APP_VERSION -o minimalweb minimalweb.go

after_success:  
  - docker build -t wenism/minimalwebgo:latest -t wenism/minimalwebgo:$APP_VERSION .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wenism/minimalwebgo:latest
  - docker push wenism/minimalwebgo:$APP_VERSION